import { Header } from './components/header'
import { FilterContextProvider } from './contexts/filter-context'
import './globals.css'
import { Saira } from 'next/font/google'
import Footer from './components/footer'

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin']
})

export const metadata = {
  title: 'HAMP Softwares',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <FilterContextProvider>
          <Header />
          {children}
        </FilterContextProvider>
      </body>
      <Footer />
    </html>
  )
}
